name 'yum-influxdb'
maintainer 'Chase Bolt'
maintainer_email 'chase.bolt@gmail.com'
license 'Apache 2.0'
description 'Installs and configures the Influxdb yum repository'
version '0.1.1'

source_url 'https://github.com/chasebolt/chef-yum-influxdb'
issues_url 'https://github.com/chasebolt/chef-yum-influxdb/issues'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
